<?= $this->doctype() ?>
<html class="no-js">
    <head>
        <?php 
        $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1');
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle('App1')->setSeparator(' - ') . PHP_EOL;
        $this->headLink()->appendStylesheet('/css/bootstrap.min.css');
        $this->headLink()->appendStylesheet('/css/bootstrap-theme.min.css');
        $this->headLink()->appendStylesheet('/css/main.css');
        echo $this->headLink() . PHP_EOL;
        $this->headStyle('body { padding-top: 50px; padding-bottom: 20px;}');
        echo $this->headStyle() . PHP_EOL;
        $this->headScript()->appendFile('/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js');
        echo $this->headScript() . PHP_EOL 
        ?>
    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    

    <div class="container">
      <?= $this->layout()->content ?>
    </div> <!-- /container -->
    
        <?php 
            $this->inlineScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js');
            $this->inlineScript()->appendScript(
            'window.jQuery || document.write(\'<script src="/js/vendor/jquery-1.10.1.min.js"><\/script>\')'
            );
            $this->inlineScript()->appendFile('/js/vendor/bootstrap.min.js');
            $this->inlineScript()->appendFile('/js/plugins.js');
            $this->inlineScript()->appendFile('/js/main.js');
            echo $this->inlineScript();
        ?>

    </body>
</html>
